<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <LangVersion>latest</LangVersion>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <RootNamespace>SympliSeoSearch.UnitTest</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.11.1"/>
        <PackageReference Include="Moq" Version="4.20.72" />
        <PackageReference Include="MSTest" Version="3.6.1"/>
        <PackageReference Include="xunit" Version="2.9.3" />
    </ItemGroup>

    <ItemGroup>
        <Using Include="Microsoft.VisualStudio.TestTools.UnitTesting"/>
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\SimpliSeoSearch.API\SimpliSeoSearch.API.csproj" />
      <ProjectReference Include="..\SimpliSeoSearch.Core\SimpliSeoSearch.Core.csproj" />
    </ItemGroup>

</Project>
